apiVersion: v1
kind: Service
metadata:
  name: svc-deployment
spec: 
  selector:
    app: springboot
  type: NodePort 
  ports:
  - port : 8082
    targetPort: 8085    
    nodePort: 31002













