apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-name
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: itdriveview/java-display-console:latest
        name: my-container
        ports:                  # ne sert à rien. à titre informatif seulement
        - containerPort: 8085   # ne sert à rien. à titre informatif seulement








