apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-name
  labels:
    app: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: itdriveview/java-display-console:latest
        name: my-container
        ports:
        - containerPort: 8085
